### ISSUE TITLE
topic_groups API is incorrect

### ISSUE THREAD

**Issue by messense** [fede1024/kafka-view#12]
https://github.com/fede1024/kafka-view/blob/b3729eb4e5af9e36f95ecfb241034d6f1cc93b53/src/web_server/api.rs#L117-L119

Here `Fn(&ClusterId, &TopicName, &String) -> bool` the second argument isn't topic name but group name cause the APIs always returns `Offsets only` state

**Comment by fede1024** [comment]
Well spotted! I'll work on a fix (unless you are already taking a stab at it).

**Comment by fede1024** [comment]
It should be fixed now. I'd love to have some tests, or integration tests, to spot this kind of bugs.
