### ISSUE TITLE
Display partition assignment in consumer group members list

### ISSUE THREAD

**Issue by messense** [fede1024/kafka-view#16]
![image](https://user-images.githubusercontent.com/1556054/31527097-c25e0ab0-af90-11e7-8c06-7fd17f51632e.png)

Add a new column `Partitions` to indicate which partitions each consumer member holds.

**Comment by fede1024** [comment]
Unfortunately this is not currently possible with the current version of rdkafka. However it should be easy to add this functionality to the library and then use it here.

**Comment by messense** [comment]
Could you elaborate more on this? I'd like to try to get it done.

**Comment by fede1024** [comment]
Sure. At the moment the rdkafka library only exports member id, client id and client host for every member of a group (see [GroupMemberInfo](https://fede1024.github.io/rust-rdkafka/rdkafka/groups/struct.GroupMemberInfo.html)). There is more information available (see [rdkafka.h](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2874)). In particular, the `member_assignment` field is the one that should contain the information that you want, but the C library afaik doesn't provide a way to decode it, so we'll have to do it manually (like [this](https://github.com/fede1024/kafka-view/blob/master/src/offsets.rs#L39)).

I think it would be great for every member to list the topic and partitions it is consuming from, not just the partition, as every member can consume from multiple topics as well. This would also require changing the format of the data on the cache topic.
